### ISSUE TITLE
Support Non-US Watchlists

### ISSUE THREAD

**Issue by compleatang** [anseljh/bgaas#1]
## UN

UN Maintains quite a few lists. They are situation (context specific) rather than collated. Mostly they are available in PDF form. 

http://www.un.org/sc/committees/list_compend.shtml
## EU

EU List (eur-lex much more data friendly, PDF is below for reference): 

http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2012:337:0002:0005:EN:PDF
## UKG

UK Government. Available in.... PDF! 

https://www.gov.uk/government/publications/current-list-of-designated-persons-terrorism-and-terrorist-financing
## Australia

Aus List:

http://www.nationalsecurity.gov.au/Listedterroristorganisations/Pages/default.aspx

**Comment by anseljh** [comment]
:thumbsup:
Thanks!
